#!/bin/bash

# LOAD THE ENVIRONMENT
module load pytorch-gpu/py3/2.8.0

# SERVE THE MOELS WITH THE CORRECT GPU ASSIGNED USING

VLLM_ENABLE_V1_MULTIPROCESSING=0 CUDA_VISIBLE_DEVICES=0 python3 new_serve_vllm.py
CUDA_VISIBLE_DEVICES=1 python3 serve_diff.py

