experiment:
  is_oracle: False

  jinja:
    env: 'templates'

    # TEXT ONLY SUMMARIES
    text_only_start_r1: 'text_only/text_only_start_r1.jinja2'
    text_only_start_r2: 'text_only/text_only_start_r2.jinja2'
    text_only_edit: 'text_only/text_only_edit.jinja2'

    # NEW OR CONTINUE OR SKIP
    meta_extraction: 'various/meta_extraction.jinja2'

    ## FOR AUGMENTER
    # For chunk + utterance to prompt for img generation
    initial_start_o: 'oracle/initial_start_oracle.jinja2'
    initial_edit_o: 'oracle/initial_edit_oracle.jinja2'

    initial_start_r1: 'vl/initial_start_real_1.jinja2'
    initial_start_r2: 'vl/initial_start_real_2.jinja2'
    initial_edit_r: 'vl/initial_edit_real.jinja2'

    final_start_t: 'vl/final_start.jinja2'
    final_edit_t: 'vl/final_edit.jinja2'

    # NEW STUFF
    caption_t: 'various/image_caption.jinja2'
    summarize_t: 'various/prompt_summarize.jinja2'
    fact_t: 'various/fact_checker.jinja2'
    triplets_extraction_t: 'various/triplets_extraction.jinja2'

  meetup:
    datapath:  "/lustre/fswork/projects/rech/bgp/ucm29gh/code/jeanzay-rl/data/IndiRef/meetup_final"
    test_case: "/lustre/fswork/projects/rech/bgp/ucm29gh/code/jeanzay-rl/data/IndiRef/meetup_final/Attributive/101_215_367_399.csv"
