# config/server_config.yaml

image_gen_service:
  host: "0.0.0.0"
  port: 8002
  model_id: "Qwen/Qwen-Image-Edit-2509"
  lora_path: "Qwen-Image-Lightning/Qwen-Image-Edit-2509/Qwen-Image-Edit-2509-Lightning-8steps-V1.0-fp32.safetensors"

image_gen_client:
  seed: 0
  num_inference_steps: 8
  true_cfg_scale: 4.0
  negative_prompt: " "

vlm_service:

  # Settings for the gateway (src/vllm_gateway.py)
  gateway: 
    host: "0.0.0.0"
    port: 8001
  
  # Settings for the vLLM server (scripts/start_vlm_service.sh)
  backend: 
    # model_id: "/lustre/fsmisc/dataset/HuggingFace_Models/Qwen/Qwen2.5-VL-32B-Instruct"
    #THINKING
    model_id: "/linkhome/rech/genxzs01/upa38qy/.cache/huggingface/hub/models--Qwen--Qwen3-VL-32B-Thinking/snapshots/7edd10ffd1196091948fb245ff63e406ccb2d4d1"
    # #INSTRUCT
    # model_id: "/linkhome/rech/genxzs01/upa38qy/.cache/huggingface/hub/models--Qwen--Qwen3-VL-32B-Instruct/snapshots/0cfaf48183f594c314753d30a4c4974bc75f3ccb"
    vllm_host: "127.0.0.1"
    vllm_port: 8008
    tensor_parallel_size: 2
    gpu_memory_utilization: 0.9
    dtype: "bfloat16"
    max_model_len: 30000  # TOTAL limit (input+output)
    trust_remote_code: true
    vllm_seed: 0

vlm_client:
  seed: 0
  top_p: 0.95
  temperature: 0.8
  max_tokens: 15000  # OUTPUT limit