# config/server_config.yaml

image_gen_service:
  host: "0.0.0.0"
  port: 8002
  model_id: "Qwen/Qwen-Image-Edit-2509"
  lora_path: "Qwen-Image-Lightning/Qwen-Image-Edit-2509/Qwen-Image-Edit-2509-Lightning-8steps-V1.0-fp32.safetensors"

image_gen_client:
  seed: 0
  num_inference_steps: 8
  true_cfg_scale: 4.0
  negative_prompt: " "

prompt_polisher_service:
  host: "0.0.0.0"
  port: 8001
  # model_id: "/linkhome/rech/genxzs01/upa38qy/.cache/huggingface/hub/models--Qwen--Qwen3-VL-32B-Thinking/snapshots/7edd10ffd1196091948fb245ff63e406ccb2d4d1"
  model_id: "/lustre/fsmisc/dataset/HuggingFace_Models/Qwen/Qwen2.5-VL-32B-Instruct"
  seed: 0
  gpu_memory_utilization: 0.9
  tensor_parallel_size: 1
  dtype: "bfloat16"
  trust_remote_code: true
  max_model_len: 15000

  vllm_host: "127.0.0.1"
  vllm_port: 8008
  vllm_seed: 0
  vllm_trust_remote_code: true

prompt_polisher_client:
  seed: 0
  top_p: 0.9
  temperature: 0.7
  max_tokens: 5000

  # These are loaded in src.api_clients.py
  jinja_env: 'templates'

  # Original from https://github.com/QwenLM/Qwen-Image/blob/main/src/examples/tools/prompt_utils.py
  polish_t: 'polish.jinja2'
  edit_t: 'polish_edit.jinja2'

  # NOT USED AT THE MOMENT
  # Modified with style-as-semantics and move/resize commands
  mod_polish_t: 'mod_polish.jinja2'
  mod_polish_edit_t: 'mod_polish_edit.jinja2'

  # For chunk + utterance to prompt for img generation
  contextual_polish_t: 'contextual_polish.jinja2'
  contextual_edit_t: 'contextual_polish_edit.jinja2'